---
title: "Report"
author: "Margaben"
date: "6/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(ggplot2)
library(dplyr)
library(highcharter)
load('./data/plots.Rdata')
load('./data/garch_data.RData')

```

# PM 10 Particles 

## Exploratory

```{r}
plot_means
```

<!-- # Monthly -->

<!-- ```{r} -->
<!-- monthly_metrics$raw_plot -->

<!-- plot(monthly_metrics$acf) -->
<!-- plot(monthly_metrics$pacf) -->

<!-- plot(monthly_metrics$decomp) -->


<!-- ``` -->

```{r}
plot(daily_metrics$ts_data,main = "TS")
```


```{r}
plot(daily_metrics$log_data,main = "Log TS")
```

```{r}
plot(daily_metrics$box_data,main = "BoxCox TS")
```

```{r fig.hold = 'hold', out.width = "50%"}
hw_grid(hchart(daily_metrics$acf) %>% hc_chart(zoomType = "x"),
hchart(daily_metrics$pacf) %>% hc_chart(zoomType = "x"),
ncol = 2)


```


```{r fig.hold = 'hold', out.width = "50%"}
hw_grid(hchart(daily_metrics$acf_log) %>% hc_chart(zoomType = "x"),
hchart(daily_metrics$pacf_log) %>% hc_chart(zoomType = "x"),
ncol = 2)

```


<!-- ```{r fig.hold = 'hold', out.width = "50%"} -->
<!-- plot(daily_metrics$acf_box,main = "ACF - Box") -->
<!-- plot(daily_metrics$pacf_box,main = "PACF - Box") -->

<!-- ``` -->
Diff
```{r}
plot(daily_metrics$decomp, "TS Components")
```

Log
```{r}
plot(daily_metrics$log_decomp, "Log TS Components")
```
Box
```{r}
plot(daily_metrics$box_decomp, "Box TS Components")
```


```{r}
hw_grid(hchart(acf(ts_ret,plot=FALSE)) %>%
          hc_chart(zoomType = "x") %>% 
          hc_yAxis(title = list(text = "ACF"),min = -0.1,max = 1) %>% 
          hc_xAxis(title = list(text = "Lag")),
hchart(acf(abs(ts_ret),plot=FALSE)) %>%
  hc_chart(zoomType = "x")%>% 
          hc_yAxis(title = list(text = "ACF"),min = -0.1,max = 1) %>% 
          hc_xAxis(title = list(text = "Lag")),
ncol = 2)
```


<!-- #### Looking at 2014 data: -->
<!-- ```{r fig.hold = 'hold', out.width = "50%"} -->
<!-- hchart(daily_metrics_2014$acf_log) -->
<!-- hchart(daily_metrics_2014$pacf_log) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- plot(daily_metrics_2014$decomp, "TS Components") -->
<!-- ``` -->
